#name of the service
spring:
  application:
    name: ApiGateway

#server ports
server:
  port: 9090

#eureka client config
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/