#name of the service
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/desettipraneeth/hrms-config-server
          clone-on-start: true
          default-label: main

#server ports
server:
  port: 8888

#eureka client config
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/